 name: attendance
 channels:
     - conda-forge
 dependencies:
     - dlib
     - pandas
     - numpy
     - face_recognition
     - pip
     - pip:
       - opencv-python
       - cmake
       - libgtk-3-dev
       - freeglut3-dev
