 name: attendance
 channels:
     - conda-forge
 dependencies:
     - dlib
     - pandas
     - numpy
     - face_recognition
     - cmake
     - libgtk-3-dev
     - freeglut3-dev
     - pip
     - pip:
       - opencv-python
       
